// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"threeSkyEXR_MZ","status":true,"description":"EXR形式の空をThree.jsで描画するプラグイン","parameters":{}},
{"name":"SkyShader_MZ","status":true,"description":"SkyShaderで青空＋雲＋太陽を描画するサンプル（RPGツクールMZ用）","parameters":{}},
{"name":"threeItemModel","status":true,"description":"アイテムオブジェクト用","parameters":{}},
{"name":"threeGroundModel","status":true,"description":"createとupdateがメインです","parameters":{}},
{"name":"threeFPSPlayer","status":true,"description":"マップ画面でWASDキーによるThree.jsカメラ操作だけを追加します✨ by サラ","parameters":{}},
{"name":"threeWorld","status":true,"description":"3D世界を構築する","parameters":{}},
{"name":"threeSurvival3D_create","status":true,"description":"createとupdateがメインです","parameters":{}},
{"name":"webAdPlugin/AdsterraAdPlaceholder","status":true,"description":"スイッチがONのときだけ広告を表示するプラグイン💕広告設定を1つにまとめました✨","parameters":{"AdSettings":"{\"AdWidth\":\"300\",\"AdHeight\":\"250\",\"AdX\":\"10\",\"AdY\":\"10\",\"ToggleSwitch\":\"2\"}"}},
{"name":"webAdPlugin/AdsterraSocialBar","status":true,"description":"AdsterraのSocial Bar広告をゲーム内に表示します。","parameters":{"ShowSwitchId":"3"}},
{"name":"webAdPlugin/AdsterraPopunder","status":true,"description":"Adsterraのポップアンダー広告を表示します（スイッチON時に1回だけ）","parameters":{"ShowSwitchId":"4"}},
{"name":"webAdPlugin/AdsterraDirectLink","status":true,"description":"Adsterraのダイレクトリンクボタンを表示します（スイッチONで表示・クリックで外部へ移動）","parameters":{"ShowSwitchId":"5","ButtonText":"広告を見る"}},
{"name":"webAdPlugin/AdsterraNativeBanner","status":true,"description":"Adsterraのネイティブバナー広告を表示するプラグイン💕スイッチでON/OFF制御も可能！","parameters":{"AdSettings":"{\"AdWidth\":\"320\",\"AdHeight\":\"100\",\"AdX\":\"10\",\"AdY\":\"10\",\"ToggleSwitch\":\"6\"}"}},
{"name":"payShop/paypalShopWebhook","status":true,"description":"PayPal連携ショッププラグイン（商品準備＋ショップ表示）💰","parameters":{}}
];
